# -*- coding: utf-8 -*-
"""textmining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-4HhCGKfGkgHCZkCg6RdMSPUhrslQpV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("Final-Dataset.csv")
print(df.head())

import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("Final-Dataset.csv")

print("Original Shape:", df.shape)
print("\nColumns:", df.columns.tolist())

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download NLTK data (run once)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('punkt', quiet=True)

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    if not isinstance(text, str) or pd.isna(text):
        return ""
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', ' ', text)          # Keep only letters
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(word) for word in tokens
              if word not in stop_words and len(word) > 2]
    return " ".join(tokens)

print("Starting text cleaning... (this may take 30–90 seconds)")

df['clean_text'] = df['FORMATTED_CONTENT'].apply(clean_text)

print(" Text cleaning completed!")

# Show before vs after
print("\n=== Before & After Cleaning ===")
for i in range(3):
    print(f"\nOriginal : {df['FORMATTED_CONTENT'].iloc[i][:150]}...")
    print(f"Cleaned  : {df['clean_text'].iloc[i][:150]}...")

# Class distribution
plt.figure(figsize=(6,4))
sns.countplot(x='CLASS', data=df, palette='Set2')
plt.title('Class Distribution (0 vs 1)')
plt.xlabel('Class')
plt.ylabel('Number of Samples')
plt.show()

print(df['CLASS'].value_counts())

# Word Cloud for Class 0 and Class 1
from wordcloud import WordCloud

def plot_wordcloud(class_num, title):
    text = " ".join(df[df['CLASS'] == class_num]['clean_text'].dropna())
    if text.strip() == "":
        print(f"No text for class {class_num}")
        return
    wc = WordCloud(width=800, height=400, background_color='white', max_words=200).generate(text)
    plt.figure(figsize=(10, 5))
    plt.imshow(wc)
    plt.axis('off')
    plt.title(title, fontsize=14)
    plt.show()

plot_wordcloud(0, "Most Common Words in CLASS 0")
plot_wordcloud(1, "Most Common Words in CLASS 1")

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, precision_recall_curve, auc
import seaborn as sns
import matplotlib.pyplot as plt

# Train-test split (stratify keeps class ratio same)
X = df['clean_text']
y = df['CLASS']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

# TF-IDF Vectorizer
vectorizer = TfidfVectorizer(max_features=10000, ngram_range=(1,2))
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

print("Vectorization done!")

# Train model
model = LogisticRegression(max_iter=1000, class_weight='balanced')  # balanced helps with imbalance
model.fit(X_train_vec, y_train)

# Predictions
y_pred = model.predict(X_test_vec)
y_pred_proba = model.predict_proba(X_test_vec)[:, 1]   # probability for CLASS 1 (spam)

# === Main Metrics ===
print("=== Classification Report ===")
print(classification_report(y_test, y_pred, target_names=['Not Spam (0)', 'Spam (1)']))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Spam', 'Spam'],
            yticklabels=['Not Spam', 'Spam'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

# ROC-AUC and PR-AUC
roc_auc = roc_auc_score(y_test, y_pred_proba)
print(f"\nROC-AUC: {roc_auc:.4f}")

precision, recall, _ = precision_recall_curve(y_test, y_pred_proba)
pr_auc = auc(recall, precision)
print(f"PR-AUC (very important for spam): {pr_auc:.4f}")

from sklearn.metrics import fbeta_score, precision_score, recall_score, classification_report

# Assuming you already have:
# y_test, y_pred from the Logistic Regression model

print("=== F-beta Scores for Spam Class (CLASS 1) ===\n")

# Calculate for different beta values
beta_values = [0.5, 1.0, 2.0]
for beta in beta_values:
    fbeta = fbeta_score(y_test, y_pred, beta=beta, pos_label=1)  # pos_label=1 for Spam
    precision = precision_score(y_test, y_pred, pos_label=1)
    recall = recall_score(y_test, y_pred, pos_label=1)

    print(f"Beta = {beta:.1f} → F{beta}-score: {fbeta:.4f}")
    print(f"   (Precision: {precision:.4f}, Recall: {recall:.4f})")

# Also show full report for comparison
print("\nFull Classification Report (includes F1):")
print(classification_report(y_test, y_pred, target_names=['Not Spam (0)', 'Spam (1)']))
